- name: Process website content
        run: |
          echo "📄 Processing website content..."
          
          BUSINESS_NAME="${{ steps.business_data.outputs.business_name }}"
          BUSINESS_CITY="${{ steps.business_data.outputs.business_city }}"
          BUSINESS_PHONE="${{ steps.business_data.outputs.business_phone }}"
          BUSINESS_EMAIL="${{ steps.business_data.outputs.business_email }}"
          INDUSTRY="${{ steps.business_data.outputs.industry }}"
          WEBSITE_URL="${{ steps.business_data.outputs.website_url }}"
          WEBSITE_HTML_BASE64="${{ steps.business_data.outputs.website_html_base64 }}"
          
          # Try to get HTML content
          HTML_SUCCESS=false
          
          # Strategy 1: Use base64 HTML from n8n (your actual generated website)
          if [ -n "$WEBSITE_HTML_BASE64" ] && [ "$WEBSITE_HTML_BASE64" != "null" ] && [ ${#WEBSITE_HTML_BASE64} -gt 100 ]; then
            echo "📥 Using base64 HTML content from n8n (your generated website)..."
            echo "$WEBSITE_HTML_BASE64" | base64 -d > website.html
            
            if [ -s website.html ]; then
              HTML_SIZE=$(wc -c < website.html)
              echo "✅ Decoded HTML content: $HTML_SIZE bytes"
              echo "🎯 This is your actual generated website with real business data!"
              HTML_SUCCESS=true
            fi
          fi
          
          # Strategy 2: Fetch from URL (if you have a live URL)
          if [ "$HTML_SUCCESS" = "false" ] && [ -n "$WEBSITE_URL" ] && [ "$WEBSITE_URL" != "null" ]; then
            echo "🌐 Fetching content from URL: $WEBSITE_URL"
            
            if curl -s -L --max-time 30 "$WEBSITE_URL" > website.html; then
              HTML_SIZE=$(wc -c < website.html)
              if [ $HTML_SIZE -gt 500 ]; then
                echo "✅ Fetched HTML content: $HTML_SIZE bytes"
                echo "🎯 Using live website content!"
                HTML_SUCCESS=true
              fi
            fi
          fi
          
          # Strategy 3: Create COMPLETELY DYNAMIC template (no more Dutch roofing!)
          if [ "$HTML_SUCCESS" = "false" ]; then
            echo "📄 Creating 100% dynamic template for: $BUSINESS_NAME"
            echo "🏭 Industry: $INDUSTRY"
            echo "📍 Location: $BUSINESS_CITY"
            
            # Set industry-specific content based on the ACTUAL data received
            case "$INDUSTRY" in
              "real_estate")
                PRIMARY_COLOR="#1e3a8a"
                SECONDARY_COLOR="#dc2626"
                TAGLINE="Professional Real Estate Services"
                SERVICE1="🏠 Property Sales"
                SERVICE2="🏢 Commercial Real Estate" 
                SERVICE3="🏡 Residential Listings"
                SERVICE4="💼 Investment Properties"
                SERVICE5="📊 Market Analysis"
                SERVICE6="🔑 Property Management"
                ;;
              "hvac")
                PRIMARY_COLOR="#dc2626"
                SECONDARY_COLOR="#1e40af"
                TAGLINE="Professional HVAC Services"
                SERVICE1="🔥 Heating Systems"
                SERVICE2="❄️ Air Conditioning"
                SERVICE3="🔧 HVAC Repair"
                SERVICE4="🛠️ Maintenance"
                SERVICE5="💨 Air Quality"
                SERVICE6="⚡ Emergency Service"
                ;;
              "restaurant")
                PRIMARY_COLOR="#dc2626"
                SECONDARY_COLOR="#92400e"
                TAGLINE="Exceptional Dining Experience"
                SERVICE1="🍽️ Fine Dining"
                SERVICE2="🥘 Catering Services"
                SERVICE3="🍕 Delivery & Takeout"
                SERVICE4="🎉 Private Events"
                SERVICE5="🍷 Bar & Cocktails"
                SERVICE6="☕ Coffee & Desserts"
                ;;
              "roofing")
                PRIMARY_COLOR="#1e40af"
                SECONDARY_COLOR="#dc2626"
                TAGLINE="Professional Roofing Services"
                SERVICE1="🏠 Roof Installation"
                SERVICE2="🔧 Roof Repair"
                SERVICE3="🛡️ Roof Maintenance"
                SERVICE4="🌧️ Gutter Services"
                SERVICE5="🔥 Roof Insulation"
                SERVICE6="⚡ Emergency Repairs"
                ;;
              *)
                # Default to generic business services
                PRIMARY_COLOR="#1f2937"
                SECONDARY_COLOR="#3b82f6"
                TAGLINE="Professional Business Services"
                SERVICE1="⭐ Premium Service"
                SERVICE2="🔧 Expert Solutions"
                SERVICE3="💼 Business Consulting"
                SERVICE4="📞 Customer Support"
                SERVICE5="🚀 Innovation"
                SERVICE6="✅ Quality Assurance"
                ;;
            esac
            
            # Create dynamic HTML with ACTUAL business data
            cat > website.html << 'HTML_EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>BUSINESS_NAME_PLACEHOLDER - TAGLINE_PLACEHOLDER</title>
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body { 
                      font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif; 
                      line-height: 1.6; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      color: #1f2937;
                  }
                  .container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }
                  .header { 
                      background: rgba(255,255,255,0.95);
                      padding: 120px 0; 
                      text-align: center; 
                      box-shadow: 0 20px 60px rgba(0,0,0,0.1);
                      backdrop-filter: blur(10px);
                  }
                  .header h1 { 
                      font-size: 5em; 
                      color: PRIMARY_COLOR_PLACEHOLDER; 
                      margin-bottom: 30px;
                      text-shadow: 2px 2px 8px rgba(0,0,0,0.1);
                      font-weight: 800;
                      letter-spacing: -2px;
                  }
                  .tagline { 
                      font-size: 2.2em; 
                      color: SECONDARY_COLOR_PLACEHOLDER; 
                      font-weight: 300;
                      margin-bottom: 20px;
                  }
                  .location {
                      font-size: 1.6em;
                      color: #6b7280;
                      margin-bottom: 40px;
                      font-weight: 500;
                  }
                  .hero-stats {
                      display: flex;
                      justify-content: center;
                      gap: 60px;
                      margin-top: 50px;
                      flex-wrap: wrap;
                  }
                  .stat {
                      text-align: center;
                      background: rgba(0,0,0,0.05);
                      padding: 30px 40px;
                      border-radius: 20px;
                      min-width: 200px;
                      backdrop-filter: blur(10px);
                  }
                  .stat-number {
                      font-size: 3.5em;
                      font-weight: 900;
                      color: SECONDARY_COLOR_PLACEHOLDER;
                      display: block;
                      line-height: 1;
                  }
                  .stat-label {
                      color: #6b7280;
                      font-size: 1.1em;
                      margin-top: 10px;
                      font-weight: 600;
                  }
                  .content { 
                      background: white; 
                      margin: 60px 0; 
                      padding: 80px 60px;
                      border-radius: 30px;
                      box-shadow: 0 30px 80px rgba(0,0,0,0.1);
                  }
                  h2 { 
                      color: PRIMARY_COLOR_PLACEHOLDER; 
                      font-size: 3.5em; 
                      margin-bottom: 50px; 
                      text-align: center;
                      font-weight: 700;
                      letter-spacing: -1px;
                  }
                  .services { 
                      display: grid; 
                      grid-template-columns: repeat(auto-fit, minmax(380px, 1fr)); 
                      gap: 40px; 
                      margin: 60px 0; 
                  }
                  .service { 
                      background: linear-gradient(135deg, PRIMARY_COLOR_PLACEHOLDER 0%, SECONDARY_COLOR_PLACEHOLDER 100%);
                      color: white;
                      padding: 50px 40px; 
                      border-radius: 25px; 
                      text-align: center;
                      transition: all 0.4s ease;
                      box-shadow: 0 15px 40px rgba(0,0,0,0.15);
                  }
                  .service:hover { 
                      transform: translateY(-20px) scale(1.02); 
                      box-shadow: 0 30px 70px rgba(0,0,0,0.25);
                  }
                  .service h3 { 
                      font-size: 2em; 
                      margin-bottom: 20px; 
                      font-weight: 700;
                  }
                  .service p { 
                      font-size: 1.2em; 
                      opacity: 0.95; 
                      line-height: 1.6;
                      font-weight: 400;
                  }
                  .contact-section { 
                      background: linear-gradient(135deg, PRIMARY_COLOR_PLACEHOLDER 0%, SECONDARY_COLOR_PLACEHOLDER 100%);
                      color: white;
                      padding: 100px 60px;
                      border-radius: 30px;
                      text-align: center;
                      margin: 60px 0;
                      box-shadow: 0 30px 80px rgba(0,0,0,0.2);
                  }
                  .contact-section h2 {
                      color: white;
                      margin-bottom: 30px;
                  }
                  .contact-intro {
                      font-size: 1.4em;
                      margin-bottom: 50px;
                      opacity: 0.95;
                      font-weight: 300;
                  }
                  .contact-info { 
                      display: grid; 
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); 
                      gap: 40px; 
                      margin-top: 50px;
                  }
                  .contact-item { 
                      background: rgba(255,255,255,0.15);
                      padding: 40px;
                      border-radius: 20px;
                      backdrop-filter: blur(20px);
                      border: 1px solid rgba(255,255,255,0.2);
                      transition: all 0.3s ease;
                  }
                  .contact-item:hover {
                      background: rgba(255,255,255,0.25);
                      transform: translateY(-5px);
                  }
                  .contact-item h4 { 
                      font-size: 1.6em; 
                      margin-bottom: 15px; 
                      font-weight: 600;
                  }
                  .contact-item p { 
                      font-size: 1.3em; 
                      font-weight: 500;
                      opacity: 0.95;
                  }
                  @media (max-width: 768px) {
                      .header h1 { font-size: 3em; }
                      .tagline { font-size: 1.6em; }
                      .hero-stats { gap: 30px; }
                      .stat { min-width: 150px; padding: 20px; }
                      .content { padding: 40px 30px; }
                      .services { grid-template-columns: 1fr; gap: 30px; }
                      .service { padding: 40px 30px; }
                      .contact-section { padding: 60px 30px; }
                      h2 { font-size: 2.5em; }
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <div class="container">
                      <h1>BUSINESS_NAME_PLACEHOLDER</h1>
                      <p class="tagline">TAGLINE_PLACEHOLDER</p>
                      <p class="location">📍 Serving BUSINESS_CITY_PLACEHOLDER</p>
                      <div class="hero-stats">
                          <div class="stat">
                              <span class="stat-number">20+</span>
                              <span class="stat-label">Years Experience</span>
                          </div>
                          <div class="stat">
                              <span class="stat-number">500+</span>
                              <span class="stat-label">Happy Clients</span>
                          </div>
                          <div class="stat">
                              <span class="stat-number">100%</span>
                              <span class="stat-label">Satisfaction</span>
                          </div>
                      </div>
                  </div>
              </div>
              
              <div class="container">
                  <div class="content">
                      <h2>Our Services</h2>
                      <div class="services">
                          <div class="service">
                              <h3>SERVICE1_PLACEHOLDER</h3>
                              <p>Professional and reliable service delivered with expertise and attention to detail.</p>
                          </div>
                          <div class="service">
                              <h3>SERVICE2_PLACEHOLDER</h3>
                              <p>Expert solutions tailored to meet your specific needs and requirements.</p>
                          </div>
                          <div class="service">
                              <h3>SERVICE3_PLACEHOLDER</h3>
                              <p>Comprehensive service offerings with guaranteed satisfaction and quality.</p>
                          </div>
                          <div class="service">
                              <h3>SERVICE4_PLACEHOLDER</h3>
                              <p>Advanced solutions designed to deliver exceptional results and value.</p>
                          </div>
                          <div class="service">
                              <h3>SERVICE5_PLACEHOLDER</h3>
                              <p>Specialized expertise to address complex challenges and opportunities.</p>
                          </div>
                          <div class="service">
                              <h3>SERVICE6_PLACEHOLDER</h3>
                              <p>Premium service options with dedicated support and professional excellence.</p>
                          </div>
                      </div>
                  </div>
                  
                  <div class="contact-section">
                      <h2>Get In Touch</h2>
                      <p class="contact-intro">Ready to work with BUSINESS_NAME_PLACEHOLDER? Contact us today for professional service you can trust.</p>
                      <div class="contact-info">
                          CONTACT_ITEMS_PLACEHOLDER
                      </div>
                  </div>
              </div>
          </body>
          </html>
          HTML_EOF
            
            # Replace placeholders with actual data
            sed -i "s/BUSINESS_NAME_PLACEHOLDER/$BUSINESS_NAME/g" website.html
            sed -i "s/BUSINESS_CITY_PLACEHOLDER/$BUSINESS_CITY/g" website.html
            sed -i "s/TAGLINE_PLACEHOLDER/$TAGLINE/g" website.html
            sed -i "s/PRIMARY_COLOR_PLACEHOLDER/$PRIMARY_COLOR/g" website.html
            sed -i "s/SECONDARY_COLOR_PLACEHOLDER/$SECONDARY_COLOR/g" website.html
            sed -i "s/SERVICE1_PLACEHOLDER/$SERVICE1/g" website.html
            sed -i "s/SERVICE2_PLACEHOLDER/$SERVICE2/g" website.html
            sed -i "s/SERVICE3_PLACEHOLDER/$SERVICE3/g" website.html
            sed -i "s/SERVICE4_PLACEHOLDER/$SERVICE4/g" website.html
            sed -i "s/SERVICE5_PLACEHOLDER/$SERVICE5/g" website.html
            sed -i "s/SERVICE6_PLACEHOLDER/$SERVICE6/g" website.html
            
            # Add contact information dynamically
            CONTACT_ITEMS=""
            if [ -n "$BUSINESS_PHONE" ] && [ "$BUSINESS_PHONE" != "null" ]; then
              CONTACT_ITEMS="$CONTACT_ITEMS<div class=\"contact-item\"><h4>📞 Phone</h4><p>$BUSINESS_PHONE</p></div>"
            fi
            if [ -n "$BUSINESS_EMAIL" ] && [ "$BUSINESS_EMAIL" != "null" ]; then
              CONTACT_ITEMS="$CONTACT_ITEMS<div class=\"contact-item\"><h4>📧 Email</h4><p>$BUSINESS_EMAIL</p></div>"
            fi
            CONTACT_ITEMS="$CONTACT_ITEMS<div class=\"contact-item\"><h4>📍 Location</h4><p>$BUSINESS_CITY</p></div>"
            
            sed -i "s/CONTACT_ITEMS_PLACEHOLDER/$CONTACT_ITEMS/g" website.html
            
            echo "✅ Created dynamic $INDUSTRY template for $BUSINESS_NAME in $BUSINESS_CITY"
            echo "🎨 Colors: Primary $PRIMARY_COLOR, Secondary $SECONDARY_COLOR"
            HTML_SUCCESS=true
          fi
          
          if [ "$HTML_SUCCESS" = "true" ]; then
            HTML_SIZE=$(wc -c < website.html)
            echo "📄 Final HTML ready: $HTML_SIZE bytes"
            echo "🎯 Business: $BUSINESS_NAME"
            echo "🏭 Industry: $INDUSTRY"
            echo "📍 Location: $BUSINESS_CITY"
          else
            echo "❌ Failed to create HTML content"
            exit 1
          fi
